source 'https://github.com/CocoaPods/Specs.git'
workspace 'LearningRecord.xcworkspace'
project 'LearningRecord/LearningRecord.xcodeproj'

platform :ios, '9.0'
inhibit_all_warnings! # 消除警告
target 'LearningRecord' do
project 'LearningRecord.xcodeproj'
	use_frameworks!

	pod 'AFNetworking', '~>3.1.0'
    pod 'Masonry', '~>1.1.0'
#    pod 'ReactiveCocoa', '~>7.1.0-rc.2'
    pod 'ReactiveObjC', '~> 3.0.0'
    pod 'MJRefresh', '~>3.1.15.1'
    pod 'SDWebImage', '~>4.2.2'
    pod 'MBProgressHUD', '~>1.1.0'
    pod 'Toast', '~>4.0.0'
end
